<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <script>

    </script>
</head>

<body>
    <h3>비동기 예외처리 (잘 모르겠다. 이후에 다시 정리)</h3>
    <script>
        function sleepAndError(g, n) {
            setTimeout(function () {
                for (var i = 0; i < n; i++) {
                    console.log(i);
                    g.throw(new Error("오류가 발생했습니다"));
                }
            }, 1000);
        }
        //  비동기 처리의 콜백 함수가 던진 예외는 콜백 함수를 넘긴 함수로 전파되지 않는다.
        function run(callback, ...argsList) {
            var g = (function* (cb, args) {
                try {
                    yield cb(g, ...args);
                } catch (e) {
                    console.log("예외를 잡음 → " + e);
                }
            })(callback, argsList);
            g.next();
        }
        run(sleepAndError, 10);
    </script>
</body>

</html>